"""Add mpesa_checkout_request_id to orders

Revision ID: 0bca7f555799
Revises: a45271847591
Create Date: 2025-05-20 10:07:37.441385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bca7f555799'
down_revision = 'a45271847591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_receipt', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mpesa_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mpesa_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('mpesa_result_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mpesa_result_desc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mpesa_transaction_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mpesa_checkout_request_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('mpesa_checkout_request_id')
        batch_op.drop_column('mpesa_transaction_date')
        batch_op.drop_column('mpesa_result_desc')
        batch_op.drop_column('mpesa_result_code')
        batch_op.drop_column('mpesa_amount')
        batch_op.drop_column('mpesa_phone')
        batch_op.drop_column('mpesa_receipt')

    # ### end Alembic commands ###
